### ISSUE TITLE
Thunderbird message count no longer showing in Plasma 5

### ISSUE THREAD

**Issue by protist** [foudfou/FireTray#178] opened 2015-05-06 23:34 UTC
I've read through the existing issues, and I can't find this specific issue. Apologies if I missed it.

I've upgraded to Plasma 5, and FireTray shows in the tray after installing libappindicator-gtk2 and libappindicator-gtk3. However, the message count is no longer showing.

I checked my FireTray preferences, and verified that `Mail` > `Enable mail notification` was checked. Oddly enough, when I looked initially, both radio buttons under `Mail notification type` were unchecked. I clicked one, but now I (obviously) cannot select no radio buttons.

Initially (with none selected), I had a Thunderbird icon in the tray at all times. Now, with the first selected, I have a Thunderbird icon when there is no new mail, and a "letter" icon when there is.

FireTray 0.5.6 59320d5 (from [here](https://github.com/foudfou/FireTray/issues/137#issuecomment-74439361))
Thunderbird 31.6.0
Arch Linux

**Comment by dannyauble** [comment] 2015-05-14 16:55
I have the same issue as well.  Is there a way to get the message count back?

**Comment by foudfou** [comment] 2015-05-15 16:10
Hi guys, this is a limitation of libappindicator.
Closing as duplicate of #143.

**Closed by foudfou** 2015-05-15 16:10 UTC

**Comment by dannyauble** [comment] 2015-05-15 16:27
Thanks for the update foudfou, is there any other option for plasma 5?  Is there a way to make it work as I can in plasma 4 (with_appindicator = false setting it in plasma 5 makes it so firetray doesn't show up at all)?  Sorry for such a noob question.  I appreciate all you have done!

**Comment by foudfou** [comment] 2015-05-15 18:26
I'm afraid there is no option for now ...and as long as nobody has time to work on #143.

**Comment by protist** [comment] 2015-05-16 07:09
Oops, sorry for the noise. I'm not sure how I missed the duplicate issue.
