### ISSUE TITLE
How to disable tray icon?? 

### ISSUE THREAD

**Issue by WeeHool** [foudfou/FireTray#150] opened 2015-01-04 15:05 UTC
Hi.
I need tip, how to disable tray icon of Firetray permanently, not only, when visible Thunderbird.
Thank you.

**Comment by foudfou** [comment] 2015-01-04 15:16
Hi, I'm not sure to understand: how about uninstalling FireTray ?

**Comment by WeeHool** [comment] 2015-01-04 15:26
Not. I am on Linux Ubuntu and show me new message in global menu. I have firetray only for stay hide open Thunderbird. After upgrade to 0.5.4 show icon in tray. Unnecessary for me.
Sorry for me english.

**Comment by Rabotyahoff** [comment] 2015-01-05 13:14
After upgrade to 0.5.4 icon always shows in system tray. But in Ubuntu unity Thunderbird integrated with indicator-messages. We need to hide firetray icon.
![tray1](https://cloud.githubusercontent.com/assets/1113031/5613474/7aa826f8-94ed-11e4-83fe-ab3717193fdd.png)

**Comment by foudfou** [comment] 2015-01-08 08:10
How about the *Show tray icon only if a window is hidden* preference ?

**Comment by Rabotyahoff** [comment] 2015-01-08 09:04
No. Thunderbird works fine on ubuntu with standart indicator-messages. And all additional icons in tray are excess.

**Comment by foudfou** [comment] 2015-01-14 23:32
Is this similar to #137 ?

**Comment by jelhan** [comment] 2015-01-15 16:41
Perhaps FireTray is wrong addon for this use case? I had the same issue and therefor switched to [MinimizeToTray revisted](https://addons.mozilla.org/en-US/thunderbird/addon/minimizetotray-revived/)

**Comment by Rabotyahoff** [comment] 2015-01-16 07:52
I think #150 similar to #137.

MinimizeToTray can't minimize window on close.

**Comment by jelhan** [comment] 2015-01-16 09:32
I'm not sure if [MinimizeToTray](https://addons.mozilla.org/de/thunderbird/addon/minimizetotray/) can, but [MinimizeToTray revisited](https://addons.mozilla.org/de/thunderbird/addon/minimizetotray-revived/) can minimize window on close. There are settings in *MinimizeToTray revistied* which controll if windows should be minimized to tray on close, on minimze, on both or never. I've german version installed otherwise I would attach an screenshot of settings.

**Comment by Rabotyahoff** [comment] 2015-01-16 10:01
jelhan thank you. It works fine!

**Comment by Zranz** [comment] 2015-01-16 16:35
FireTray has more options than [MinimizeToTray revisited](https://addons.mozilla.org/de/thunderbird/addon/minimizetotray-revived/). For instance "Start application hidden on tray" which I find incredibly useful.

So adding an option to disable the icon would be great, in particular for Ubuntu users.

**Comment by hieinji** [comment] 2015-01-16 19:29
I agree with Zranz.

2015-01-16 17:35 GMT+01:00 Zranz <notifications@github.com>:

**Comment by foudfou** [comment] 2015-02-15 21:58
Closing this one as duplicate of #137. See [this fix](/foudfou/FireTray/issues/137#issuecomment-74439361). Can you provide feedback there ?

**Closed by foudfou** 2015-02-15 21:58 UTC

**Comment by Mrfuyu** [comment] 2016-08-15 18:52
To always hide the tray icon you can select the user defined icon under 'symbol' and leave the field empty.

**Comment by zranz** [comment] 2016-08-16 08:55
Your suggested fix does not work. After sending thunderbird to the tray, default icon reappears.

**Comment by Mrfuyu** [comment] 2016-08-18 21:28
With Xfce it works. Unity behaves different seemingly.
