### ISSUE TITLE
Problems with more than one window

### ISSUE THREAD

**Issue by allopislozano** [foudfou/FireTray#189] opened 2015-06-26 10:53 UTC
When  "Closing window hides to tray" is enabled, it has some problems with more than one window.

It should ignore this option for non-main window or provide a way to really close a window. 

Expected behaviour: exiting TB would close all windows except main one

Observed behaviour: impossible to close additional (child) windows. When reopening TB, it always remembers all the windows that were at some point open

**Comment by RalfJung** [comment] 2015-08-24 11:44
I can confirm this problem: When I (accidentally) open a 2nd window, it is really hard to get rid of it. The only way I found so far is to: Disable FIreTray, restart Thunderbird, close all but one window, restart Thunderbird, enable FireTray, restart Thunderbird. As long as FireTray is active, it is impossible to get rid of the additional window.

**Comment by foudfou** [comment] 2015-08-24 14:04
Hi, how about the `only last window can be hidden` preference ?
I'm not 100% sure what exactly the problem is, or what you are trying to achieve, but with `Closing window hides to tray`, you should close windows with *Ctrl-W*.

**Comment by RalfJung** [comment] 2015-08-24 14:08
> Hi, how about the `only last window can be hidden` preference ?

Yes, that seems to do it! But sane behavior shouldn't be optional

> I'm not 100% sure what exactly the problem is, or what you are trying to achieve, but with `Closing window hides to tray`, you should close windows with *Ctrl-W*.

With the configuration I previously had, once there are two Thunderbird
windows, it becomes impossible (from the UI, not knowing about Ctrl-W)
to close one of them. If I hit the "X" button, the window will come back
the next time I hide and show the main window, or the next time I
restart Thunderbird. It's like the window rising from the grave again
and again, with no way to properly kill it once and forever... really,
there should be no way to configure Thunderbird in a way that this happens.

**Comment by foudfou** [comment] 2015-08-24 21:39
Since the issue is resolved, I'll close this one. Feel free to reopen if I missed something.

**Closed by foudfou** 2015-08-24 21:39 UTC

**Comment by RalfJung** [comment] 2015-08-25 07:07
So you are saying, "the user is unable to close a window" is expected behavior? Really, I can't think of any situation where "Closing window hides to tray" does *not* mean "Closing *the last window* hides to tray". If anything else is even offered, it should *not* be the default, and should have some form of telling the user about Ctrl-W. So, from a usability perspective, please re-consider whether you want to offer your users this footgun.
