### ISSUE TITLE
Doesn't work on Windows 7 [Thunderbird v31.5.0]

### ISSUE THREAD

**Issue by RuslanYanyuk** [foudfou/FireTray#173] opened 2015-03-17 20:53 UTC
Hi guys,

I have faced with a little problem. The firetray refuses to work because of new separator in Thunderbird window title. I mean it used to be like "name@mail - Mozilla Tunderbird" but now it's "name@mail — Mozilla Tunderbird". And that breaks logic at modules\FireTrayWindow.jsm line 30.

tailIndex = title.indexOf(" - Mozilla "+firetray.Handler.appName);

Please, consider a good fix.)
Thanks.

**Comment by RuslanYaniuk** [comment] 2015-03-21 19:00
This one should work
tailIndex = title.indexOf(" " + '\u2014' + " Mozilla "+firetray.Handler.appName);

**Comment by foudfou** [comment] 2015-03-22 21:17
Hi,
Can't reproduce the problem. Tested with win8.1 and win7, Thunderbird 32 and 37.
It should not fail at modules\FireTrayWindow.jsm line 30, because 1. the test doesn't throw, and 2. further tests are made afterwards.
Do you run a special version of Thunderbird (Beta/Developer/...) ?
Do you have any other extensions that might modify the window title ? If so can you test in a fresh profile (`thunderbird -P`) ?
What firetray-related messages do you get in the Error console ?

**Comment by RuslanYaniuk** [comment] 2015-03-23 08:47
I am using standard version of Thunderbird.
I have installed Exquilla too but I think it shouldn't affect the window title.
I think it might be a localization problem, because my OS has Ukrainian localization.
There was an JS error (sorry, can not remember what was the messages now) because  a function that holds line 30 returns null.
I'll test it with a new profile and let you know tomorrow.

**Comment by RuslanYaniuk** [comment] 2015-03-23 18:14
It looks like I found root of the problem. It doesn't depend on what system locale is, that depends on localization of Thunderbird. I tested Ukrainian build of Thunderbird and English build on Windows 7 Ukrainian and english build has seperator as simple dash. You can take a look on 
 those screenshots I made.
English build:
![win7ua-with_english_build_of_thunderbird](https://cloud.githubusercontent.com/assets/10400729/6787098/25dcc4d8-d199-11e4-89f4-517deaaf24dd.png)
Ukrainian build:
![win7ua-with_ukrainian_build_of_thunderbird](https://cloud.githubusercontent.com/assets/10400729/6787047/b6b4f15c-d198-11e4-8770-8dabf3ff6701.png)

**Comment by foudfou** [comment] 2015-03-25 01:28
Should be fixed in a2c0d655a037.
Although you don't explain what "firetray refuses to work" means...

**Comment by RuslanYaniuk** [comment] 2015-03-25 19:22
I meant it's not working. When I click minimize button the Thunderbird window it doesn't respond to the action and the JS  console has an error message 'parameter must be an array or string', when I click the close button it closes the Thunderbird but not hides it to tray.

**Comment by foudfou** [comment] 2015-04-06 21:25
Can you try (v05.5.5)[https://addons.mozilla.org/fr/firefox/addon/firetray/versions/?page=1#version-0.5.5] and confirm it works ?

**Comment by RuslanYanyuk** [comment] 2015-04-07 18:17
I couldn't download the v05.5.5. For some reason it's not present on that page but there was a build I tested v0.5.5.6 and it works fine on Win7 with US and Ukrainian Thunderbird builds v31.1.0. 
Thanks.

**Comment by foudfou** [comment] 2015-04-07 20:12
Great! Thanks

**Closed by foudfou** 2015-04-07 20:12 UTC
