### ISSUE TITLE
Plasma 5 support

### ISSUE THREAD

**Issue by filipesaraiva** [foudfou/FireTray#130] opened 2014-08-15 17:34 UTC
Hello, first thanks for this great Thunderbird addon.

Plasma 5, the new version of KDE's Plasma Desktop, drop-out the xembed based system tray. There are some alternatives to fix it, you can read in http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

So, do you provide support to Plasma 5?

Thank you!

**Comment by Rabotyahoff** [comment] 2015-01-05 10:06
How to hide icon in system tray? Because I use unity and Thunderbird integrated with indicator-messages. I don't like many items in tray.

**Comment by foudfou** [comment] 2015-01-05 10:39
@Rabotyahoff is your request related to #150 ? If so could you explain your needs precisely on #150 ?

**Comment by xylo** [comment] 2015-01-12 10:17
I wonder that this discussion is only about KDE 5.  I'm using KDE 4.13.3 and Thunderbird 31.3.0 with FireTray 0.5.4 and discovered the same problems:
- tray icon does not show the number of unread messages anymore
- left click on tray icon does not work anymore
- scroll up / down on tray icon does also not work

Some weeks ago everything worked fine but something major has changed and broke the entire add-on.

**Comment by xylo** [comment] 2015-01-12 10:33
OK, I found another bug report that addresses only the feature regression in version 0.5.4: https://github.com/foudfou/FireTray/issues/151

**Comment by foudfou** [comment] 2015-01-14 23:24
Ok. I'll close this one, as support for Plasma 5 is covered, although not perfect.
I think the `with_appindicator` preference deserves UI but that's another issue.
Also the appindicator doesn't provide as much functionality as with EWMH icons (#143).

**Closed by foudfou** 2015-01-14 23:24 UTC
Labels: AppInd

**Comment by ScorpionIT** [comment] 2015-05-31 12:55
http://jjacky.com/statusnotifier/

**Comment by Rush** [comment] 2015-05-31 12:58
@ScorpionIT does it have right click support? The Ubuntu focused solutions usually only support left-click. My library supports right click event https://github.com/encharm/libsystemtray and is super simple, doesn't require even GLib.

**Comment by ScorpionIT** [comment] 2015-05-31 13:03
it support left,right,middle click and scroll

**Comment by ScorpionIT** [comment] 2015-05-31 16:07
@Rush I had a look at your library and it is very nice.
I have compiled it but when i launch the test binary I don't see the icon in the tray

**Comment by gshegosh** [comment] 2015-07-29 13:42
For what it's worth, Skype somehow does the tray icon with left and right click working, I have no idea how. Missing tray icon left click support for Thunderbird and Pidgin is a pain :-( I've tried looking at source codes, but KDE development is not my pair of shoes :-(

**Comment by ohhai** [comment] 2015-08-01 20:38
Skype requires sni-qt package for that in KDE 5. For GTK apps installing libappindicator may help.

**Comment by Rush** [comment] 2015-08-02 19:56
@ScorpionIT it is fixed, have you given it a second shot?

**Comment by kF13Ld** [comment] 2015-09-03 19:26
As I am also running plasma 5 (as well as probably a lot of more people), would you guys mind publishing a new version of FireTray?

**Comment by foudfou** [comment] 2015-09-03 19:39
@kF13Ld I'm willing to do this shortly. We must also take the [time for review process](https://blog.mozilla.org/addons/2015/09/02/add-ons-update-70/) into account...
Meanwhile, you may want to [build for yourself](/foudfou/FireTray/wiki/Build).

**Comment by kF13Ld** [comment] 2015-09-06 13:51
@foudfou: Ok, compiling indeed worked, but what was not mentioned in your how to was to change the line 11 in the file `src/logging.jsm` from
`const FIRETRAY_LOG_LEVEL = "All"; // "All" for debugging`
to 
`const FIRETRAY_LOG_LEVEL = "Warn"; // "All" for debugging`.
Otherwise it would not compile (forgot error message).

After installing the plugin, you can see the result here:
![thunderbird_firetray_no_icon](https://cloud.githubusercontent.com/assets/13854565/9704661/9b3dc3ec-54ae-11e5-8e6f-a6ab344bc98f.png)

The icon does not show, but it is there. I.e. I can right click on it to get the context menu, and middle click to open the thunderbird window.

Also, for new messages, a letter symbol correctly appears. But for some reasons, the normal thunderbird icon is invisible. I have already tried setting a custom icon, with no help.

**Comment by foudfou** [comment] 2015-09-07 20:28
@kF13Ld , I can confirm this new issue (missing icons for plasma 5). Tested on Fedora22.
I'm created a new issue #199. Please follow up there.

**Comment by juanluisbaptiste** [comment] 2016-02-11 21:41
Is there a released version that includes this fix ? currently I'm testing firetray 0.6.0.1-let-fixed on kubuntu 15.10 and the system tray icon still doesn't appear.

**Comment by juanluisbaptiste** [comment] 2016-02-11 22:16
But building git version works as described here.
