### ISSUE TITLE
Ampersand not escaped in mail notification

### ISSUE THREAD

**Issue by rkraats** [foudfou/FireTray#171] opened 2015-03-12 13:31 UTC
When I receive a mail with an ampersand (&) in the subject, the mail notification window/pop-up doesn't show the subject. /var/log/messages explains why:

> Mar 12 14:19:54 roel org.freedesktop.Notifications: (xfce4-notifyd:23346): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;

Using 0.5.4 on Fedora 21 running xfce.

**Comment by foudfou** [comment] 2015-03-12 15:29
Hi, FireTray has nothing to do with the email notifications window.
Looks like this issue has been reported already around:
https://bugzilla.redhat.com/show_bug.cgi?id=1001998
https://github.com/mkiol/GNotifier/issues/9
https://bugzilla.mozilla.org/show_bug.cgi?id=853104
I'll close this one as INVALID, but feel free to reopen if you think FireTray might be the cause.

**Closed by foudfou** 2015-03-12 15:29 UTC

**Comment by rkraats** [comment] 2015-03-12 15:33
Whoops! I always thought that FireTray shows these notification windows. Sorry about my mistake. And thanks for the quick response!

   Roel
