### ISSUE TITLE
Constant random crashes

### ISSUE THREAD

**Issue by protist** [foudfou/FireTray#192] opened 2015-07-08 06:02 UTC
I initially reported this bug (incorrectly) as a comment to issue #152.

TB has been crashing for me since I upgraded to TB 38.0.1 (in Arch Linux). It launches fine, but crashes within a few minutes, even if starting from the command line. I have replicated this over a dozen times, and it crashes 100% of the time. If I disable Firetray, then it works fine. I built Firetray from source (0.5.7pre1) for debugging purposes. [Here](https://gist.github.com/protist/4a078814b310fe04836c) is the output on the command line, although I'm not sure how informative it is.

TB 38.0.1
Arch Linux
KDE Plasma 5.3.2 (also 5.3.1)
gtk2 2.24.28
gtk3 3.16.4

I've since tried downgrading Firetray. I can confirm that TB crashes within minutes for `0.5.7pre1`, `0.5.6.1-signed`, and `0.5.4.1-signed`. `0.5.3.1-signed.1-signed` doesn't crash TB, but obviously lacks tray support for KDE Plasma 5.

I've isolated the issue to a conflict with the add-on [Virtual Identity 0.9.33](https://www.absorb.it/virtual-id). If I disable either add-on, TB will not crash. Alternatively, I can make TB crash at will if I only enable these two add-ons.

I've tried to reproduce this crash in a VirtualBox environment but for some reason cannot. FWIW I also tried totally uninstalling both, removing all entries in about:config related to either add-on, then reinstalling. This did not prevent crashes.

**Comment by protist** [comment] 2015-07-25 05:49
I can replicate this bug on my wife's computer, which does not have Virtual Identity installed. TB crashes consistently with FireTray as the only extension installed. In an attempt to isolate the bug, I copied her TB directory to my computer, but could no longer replicate the bug! We're both using Arch Linux with KDE Plasma 5, so I'm not sure how to progress.

**Comment by protist** [comment] 2015-08-03 13:07
Quite possibly I'm facing the same bug as #177 and #153, but I can't really test it. If I remove `libappindicator-gtk2`, `libappindicator-gtk3` and associated dependencies, FireTray won't crash TB. However, I get no tray icon in Plasma 5, so presumably it's not a very specific test.

**Comment by dh4** [comment] 2015-08-10 18:57
Same issue on Arch Linux without Virtual Identity:
Thunderbird 38.1.0
FireTray 0.5.6
KDE Plasma 5.3.2
GTK 2.24.28
libappindicator 12.10.0

The following is printed to the console when Thunderbird freezes:
> (thunderbird:10951): GLib-GObject-WARNING **: cannot register existing type 'GdkKeymap'
> 
> (thunderbird:10951): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
> 
> (thunderbird:10951): Gdk-CRITICAL **: gdk_keymap_have_bidi_layouts: assertion 'GDK_IS_KEYMAP (keymap)' failed

Only happens with FireTray enabled.

**Comment by ryhaberecht** [comment] 2015-09-01 00:44
Same issue on Debian Jessie.

Qt: 4.8.6
KDE Development Platform: 4.14.2
Plasma Desktop Shell: 4.11.13
Icedove (Thunderbird) 31.8.0
libappindicator3-1 0.4.92-3.1

FireTray 0.5.3.1 seems to work fine so far, though.

**Comment by jackyohh** [comment] 2015-10-03 13:17
Same issue on Debian Sid

Qt: 5.4.2
KDE Plasma: 5.4.1
Icedove (Thunderbird): 38.2.0
Iceweasel (Firefox): 38.3.0
libappindicator3-1: 0.4.92-3.1

FireTray 0.5.3.1 (and 0.5.7pre1) crashes ff and tb when i click thumb buttons on my mouse. then i get same error
(iceweasel:30963): GLib-GObject-WARNING **: cannot register existing type 'GdkKeymap'
(iceweasel:30963): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(iceweasel:30963): Gdk-CRITICAL **: gdk_keymap_have_bidi_layouts: assertion 'GDK_IS_KEYMAP (keymap)' failed

**Comment by ka223** [comment] 2015-10-07 18:49
Have the same for some time now with TB 38.3.0 on Xubuntu 14.04 64Bit.
Both my thunderbird profiles where unreachable, tray icon gone and the thunderbird process is still running.

Same error messages at the terminal:
[code](thunderbird:3348): GLib-GObject-WARNING **: cannot register existing type 'GdkKeymap'

(thunderbird:3348): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(thunderbird:3348): Gdk-CRITICAL **: gdk_keymap_have_bidi_layouts: assertion 'GDK_IS_KEYMAP (keymap)' failed
[/code]

**Comment by ArMoraer** [comment] 2015-10-09 00:55
Exact same issue since yesterday (Ubuntu 12.04 64b, TB 38.3.0 FireTray 0.5.6.1-signed). After a few minutes, TB cannot be opened anymore from the tray bar. Sometimes the tray icon also disappears, though not always.

**Comment by devbo1** [comment] 2015-10-10 18:46
Same issue with;
Ubuntu 14.04.3 LTS
Thunderbird 38.3.0
FireTray 0.5.6-signed
Ubuntu 14.04.3 LTS

Thunderbird is unusable after several minutes or just minimizing to tray.
Following error is displayed:

``` bash
(thunderbird:29451): GLib-GObject-WARNING **: cannot register existing type 'GdkKeymap'

(thunderbird:29451): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(thunderbird:29451): Gdk-CRITICAL **: gdk_keymap_have_bidi_layouts: assertion 'GDK_IS_KEYMAP (keymap)' failed
```

**Comment by coolka** [comment] 2015-10-12 09:13
I have same error whenever i use mute/volume up/volume down buttons on my keyboard. It started less than month ago

```
(thunderbird:5473): GLib-GObject-WARNING **: cannot register existing type 'GdkKeymap'
(thunderbird:5473): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(thunderbird:5473): Gdk-CRITICAL **: gdk_keymap_have_bidi_layouts: assertion 'GDK_IS_KEYMAP (keymap)' failed
```
Ubuntu 15.04, Plasma 5.2.2

**Comment by boussouira** [comment] 2015-10-13 09:13
Freezenig thunderbird 38.3.0 on Linux (debian based) with firetray 0.5.6.1.

Work around: Use older addon. At my case version 0.5.3.x working without any problems.

**Comment by protist** [comment] 2015-10-13 09:19
@boussouira So that is consistent with my testing in the first post. However, that version lacks support for the newer versions of KDE Plasma.

**Comment by boussouira** [comment] 2015-10-13 09:27
can you set `extensions.firetray.with_appindicator` to false in `about:config` and try to reproduce the crash?

**Comment by protist** [comment] 2015-10-13 11:14
@boussouira I've actually stopped using Thunderbird now for a number of reasons (including the lack of a tray icon). From memory I tried this, but I think it prevented the tray icon from working at all. If any of the other bug subscribers want to try, please feel free.

**Comment by coolka** [comment] 2015-10-13 11:20
@boussouira i've checked this setting, but no change on thunderbird. Dies with same message as before

**Comment by foudfou** [comment] 2015-10-13 12:29
Does [v0.6.0](https://addons.mozilla.org/en-US/firefox/addon/firetray/versions/0.6.0) solve the issue ?

**Comment by foudfou** [comment] 2015-10-13 12:31
@protist what mail client do you use now ?

**Comment by protist** [comment] 2015-10-13 12:39
@foudfou I'm using mutt. It doesn't have a tray icon, of course, but I'm finding it much better than Thunderbird in many other ways (after the learning curve!). FWIW I've hacked together my own tray icon using [imapnotify](https://github.com/a-sk/node-imapnotify), which triggers a count of the `new` maildir folders, which is then displayed in a [textbox](https://github.com/arcan1s/awesome-widgets) in KDE Plasma's panel.

**Comment by coolka** [comment] 2015-10-13 12:40
@foudfou yes for me v0.6.0 solved problem. Thanks

**Comment by ryhaberecht** [comment] 2015-10-13 16:25
0.6.0 fixes bug on Debian Jessie as well!

**Comment by foudfou** [comment] 2015-10-13 18:33
@protist thx. I must say mutt is tempting!
Closing this one then.

**Closed by foudfou** 2015-10-13 18:33 UTC

**Comment by protist** [comment] 2015-10-14 09:31
@foudfou I can definitely recommend it, but I've spent something like 30+ hours tweaking it so far! Be prepared for the (short-term) time sink!
