### ISSUE TITLE
Thunderbird 38b6

### ISSUE THREAD

**Issue by tom62** [foudfou/FireTray#185] opened 2015-06-11 11:22 UTC
FireTray (built from commit 135126a) does not work with Icedove (from experimental repository) or with Thunderbird 38b6 (from Ubuntu PPA) on Debian Jessie. When I close the Thunderbird window, the icon in the tray disappears and I get following:
```
13:13:9.347 ERROR firetray.FiretrayWindow unknown window while lookup
13:13:9.347 ERROR firetray.Window can't unregister unknown window nul
```

**Comment by foudfou** [comment] 2015-06-11 12:20
Hi, can you provide [further informations](/foudfou/FireTray/wiki/Submit-a-bug) ?

**Comment by tom62** [comment] 2015-06-11 16:06
FireTray version: 0.5.6.1 or commit 135126a
Mozilla application + version: Icedove 38b5 (from Debian experimental repository) or Thunderbird 38b6 (from Ubuntu PPA)
Linux distro version: Debian Jessie
Desktop environment (if any): KDE 4.14.2 (from Jessie repositories)
Window manager: KWin
GTK+ version: 2.24.25, 3.14.5

Log from debug vestion (I started Thunderbird and than closed it, so it should close to tray, but it crashed):
```
(process:7193): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[calBackendLoader] Using libical backend at /usr/lib/thunderbird/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}/components/libical-manifest
14:24:35.648 DEBUG firetray.Logging initialized
14:24:35.659 DEBUG firetray.Handler _directory=/home/MYUSER/.thunderbird/MYUSER/extensions/{9533f794-00b4-4354-aa15-c2bbda6989f8}
JavaScript error: chrome://messenger/content/tabmail.xml, line 1067: TypeError: tab is undefined
14:24:39.800 DEBUG firetray.Chrome Handler initialized: false
14:24:39.800 INFO firetray.Handler OS=linux, ABI=x86_64-gcc3, XULrunner=38.0
14:24:39.803 INFO firetray.ctypes-utils is64bit=true
14:24:39.804 DEBUG firetray.ctypes-utils Trying to load library: cairo
14:24:39.804 DEBUG firetray.ctypes-utils Trying libcairo.so.2
14:24:39.805 DEBUG firetray.ctypes-utils Successfully loaded libcairo.so.2
14:24:39.805 DEBUG firetray.ctypes-utils Trying to load library: glib-2.0
14:24:39.806 DEBUG firetray.ctypes-utils Trying libglib-2.0.so.0
14:24:39.806 DEBUG firetray.ctypes-utils Successfully loaded libglib-2.0.so.0
14:24:39.807 DEBUG firetray.ctypes-utils Trying to load library: gobject-2.0
14:24:39.807 DEBUG firetray.ctypes-utils Trying libgobject-2.0.so.0
14:24:39.807 DEBUG firetray.ctypes-utils Successfully loaded libgobject-2.0.so.0
14:24:39.809 DEBUG firetray.ctypes-utils Trying to load library: X11
14:24:39.809 DEBUG firetray.ctypes-utils Trying libX11.so.6
14:24:39.810 DEBUG firetray.ctypes-utils Successfully loaded libX11.so.6
14:24:39.810 DEBUG firetray.ctypes-utils Trying to load library: gdk-x11-2.0
14:24:39.811 DEBUG firetray.ctypes-utils Trying libgdk-x11-2.0.so.0
14:24:39.811 DEBUG firetray.ctypes-utils Successfully loaded libgdk-x11-2.0.so.0
14:24:39.814 DEBUG firetray.ctypes-utils Trying to load library: gio-2.0
14:24:39.814 DEBUG firetray.ctypes-utils Trying libgio-2.0.so.0
14:24:39.814 DEBUG firetray.ctypes-utils Successfully loaded libgio-2.0.so.0
14:24:39.815 DEBUG firetray.ctypes-utils Trying to load library: c
14:24:39.815 DEBUG firetray.ctypes-utils Trying libc.so.6
14:24:39.815 DEBUG firetray.ctypes-utils Successfully loaded libc.so.6
14:24:39.821 DEBUG firetray.ctypes-utils Trying to load library: pango-1.0
14:24:39.821 DEBUG firetray.ctypes-utils Trying libpango-1.0.so.0
14:24:39.821 DEBUG firetray.ctypes-utils Successfully loaded libpango-1.0.so.0
14:24:39.821 DEBUG firetray.ctypes-utils Trying to load library: gtk-x11-2.0
14:24:39.821 DEBUG firetray.ctypes-utils Trying libgtk-x11-2.0.so.0
14:24:39.821 DEBUG firetray.ctypes-utils Successfully loaded libgtk-x11-2.0.so.0
14:24:39.823 DEBUG firetray.ctypes-utils Trying to load library: appindicator3
14:24:39.823 DEBUG firetray.ctypes-utils Trying libappindicator3.so.1
14:24:39.823 INFO firetray.ctypes-utils Library does not exist: appindicator3
14:24:39.824 INFO firetray.StatusIcon desktop={"name":"kde","ver":4}
14:24:39.824 DEBUG firetray.Handler FiretrayStatusIcon linux imported
14:24:39.824 INFO firetray.Handler useAppind=false
14:24:39.829 DEBUG firetray.Window x11.current.Atoms.WM_DELETE_WINDOW=323
14:24:39.829 DEBUG firetray.Window x11.current.Atoms.WM_STATE=329
14:24:39.829 DEBUG firetray.Window x11.current.Atoms.WM_CHANGE_STATE=330
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_MODAL=369
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_STICKY=465
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_MAXIMIZED_VERT=368
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_MAXIMIZED_HORZ=367
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_SHADED=498
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_SKIP_TASKBAR=463
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_SKIP_PAGER=464
14:24:39.830 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_HIDDEN=499
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_FULLSCREEN=366
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_ABOVE=364
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_BELOW=365
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE_DEMANDS_ATTENTION=371
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_CLOSE_WINDOW=486
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_NAME=358
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_VISIBLE_NAME=488
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_ICON_NAME=359
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_VISIBLE_ICON_NAME=489
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_DESKTOP=462
14:24:39.831 DEBUG firetray.Window x11.current.Atoms._NET_WM_WINDOW_TYPE=375
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_STATE=363
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_ALLOWED_ACTIONS=494
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_STRUT=490
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_STRUT_PARTIAL=491
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_ICON_GEOMETRY=492
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_ICON=360
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_PID=361
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_HANDLED_ICONS=493
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_WM_USER_TIME=372
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_FRAME_EXTENTS=460
14:24:39.832 DEBUG firetray.Window x11.current.Atoms._NET_ACTIVE_WINDOW=397
14:24:39.833 DEBUG firetray.Window x11.current.Atoms.CARDINAL=6
14:24:39.833 DEBUG firetray.Handler FiretrayWindow linux imported
14:24:39.833 INFO firetray.Handler inMailApp=true, inBrowserApp=false, appHasChat=true
14:24:39.839 DEBUG firetray.ctypes-utils Trying to load library: pangocairo-1.0
14:24:39.839 DEBUG firetray.ctypes-utils Trying libpangocairo-1.0.so.0
14:24:39.840 DEBUG firetray.ctypes-utils Successfully loaded libpangocairo-1.0.so.0
14:24:39.843 DEBUG firetray.PopupMenu cbName=menuItemResetIconActivate
14:24:39.843 DEBUG firetray.PopupMenu cbName=menuItemNewMessageActivate
14:24:39.844 DEBUG firetray.PopupMenu cbName=menuItemPreferencesActivate
14:24:39.844 DEBUG firetray.PopupMenu cbName=menuItemQuitActivate
14:24:39.844 DEBUG firetray.PopupMenu cbName=menuItemActivateLastActivate
14:24:39.845 DEBUG firetray.PopupMenu cbName=menuItemShowHideActivate
14:24:39.845 DEBUG firetray.commons file:///home/MYUSER/.thunderbird/MYUSER/extensions/%7B9533f794-00b4-4354-aa15-c2bbda6989f8%7D/chrome/skin/icons/blank-icon.png
14:24:39.845 DEBUG firetray.commons file:///home/MYUSER/.thunderbird/MYUSER/extensions/%7B9533f794-00b4-4354-aa15-c2bbda6989f8%7D/chrome/skin/icons/linux
14:24:39.845 DEBUG firetray.GtkIcons /home/MYUSER/.thunderbird/MYUSER/extensions/{9533f794-00b4-4354-aa15-c2bbda6989f8}/chrome/skin/icons/linux
14:24:39.846 DEBUG firetray.GtkIcons gtkIconTheme=GtkIconTheme.ptr(ctypes.UInt64("0x7fa3649ddb70"))
14:24:39.859 DEBUG firetray.GtkIcons n_elements=ctypes.int(10) path=ctypes.char.ptr.ptr(ctypes.UInt64("0x7fa34ec82f40"))
14:24:39.859 DEBUG firetray.GtkIcons path[0]=/home/MYUSER/.kde/share/icons
14:24:39.859 DEBUG firetray.GtkIcons path[1]=/home/MYUSER/.icons
14:24:39.859 DEBUG firetray.GtkIcons path[2]=/home/MYUSER/.local/share/icons
14:24:39.859 DEBUG firetray.GtkIcons path[3]=/usr/share/icons
14:24:39.859 DEBUG firetray.GtkIcons path[4]=/usr/share/icons
14:24:39.859 DEBUG firetray.GtkIcons path[5]=/usr/local/share/icons
14:24:39.860 DEBUG firetray.GtkIcons path[6]=/usr/share/pixmaps
14:24:39.860 DEBUG firetray.GtkIcons path[7]=/usr/share/pixmaps
14:24:39.860 DEBUG firetray.GtkIcons path[8]=/usr/local/share/pixmaps
14:24:39.860 DEBUG firetray.GtkIcons path[9]=/home/MYUSER/.thunderbird/MYUSER/extensions/{9533f794-00b4-4354-aa15-c2bbda6989f8}/chrome/skin/icons/linux
14:24:39.860 DEBUG firetray.GtkIcons path=ctypes.char.ptr.ptr(ctypes.UInt64("0x7fa34ec82f40")) pathIt=ctypes.char.ptr.ptr(ctypes.UInt64("0x7fa34ec82f90"))
14:24:39.860 DEBUG firetray.GtkStatusIcon themedIconNames=indicator-messages-new,mail-message-new,mail-unread
14:24:39.860 DEBUG firetray.GtkStatusIcon themedIconNamesLen=3
14:24:39.860 DEBUG firetray.GtkStatusIcon themedIconNames=ctypes.char.ptr.array(3)([ctypes.char.ptr(ctypes.UInt64("0x7fa35ccb2940")), ctypes.char.ptr(ctypes.UInt64("0x7fa35ccb29a0")), ctypes.char.ptr(ctypes.UInt64("0x7fa35cb10190"))])
14:24:39.861 DEBUG firetray.GtkStatusIcon themedIcon=GIcon.ptr(ctypes.UInt64("0x7fa34ede9b80"))
14:24:39.861 DEBUG firetray.GtkStatusIcon themedIconNames=indicator-messages,applications-email-panel,thunderbird
14:24:39.861 DEBUG firetray.GtkStatusIcon themedIconNamesLen=3
14:24:39.861 DEBUG firetray.GtkStatusIcon themedIconNames=ctypes.char.ptr.array(3)([ctypes.char.ptr(ctypes.UInt64("0x7fa35ccb2d60")), ctypes.char.ptr(ctypes.UInt64("0x7fa35ccb2dc0")), ctypes.char.ptr(ctypes.UInt64("0x7fa35cb101e0"))])
14:24:39.861 DEBUG firetray.GtkStatusIcon themedIcon=GIcon.ptr(ctypes.UInt64("0x7fa34ede9c10"))
14:24:39.864 DEBUG firetray.GtkStatusIcon setIconImageDefault
14:24:39.864 DEBUG firetray.GtkStatusIcon GIcon.ptr(ctypes.UInt64("0x7fa34ede9c10"))
14:24:39.865 DEBUG firetray.GtkStatusIcon setIconTooltip, toolTipStr=Thunderbird
14:24:39.865 DEBUG firetray.GtkStatusIcon showHideAllWindows: true
14:24:39.865 DEBUG firetray.GtkStatusIcon g_connect activate=520
14:24:39.865 DEBUG firetray.GtkStatusIcon g_connect middleClick=521
14:24:39.866 DEBUG firetray.Handler allWindowsVisible=true msgCountPositive=true
14:24:39.866 DEBUG firetray.Handler StatusIcon initialized
14:24:39.868 DEBUG firetray.Messaging Enabling Messaging
14:24:39.868 DEBUG firetray.Messaging updateMsgCountWithCb
14:24:39.868 DEBUG firetray.Messaging msgCountType=0
14:24:39.869 DEBUG firetray.Messaging mail accounts from pref: {"serverTypes":{"pop3":{"order":1,"excluded":true},"imap":{"order":1,"excluded":false},"movemail":{"order":2,"excluded":true},"none":{"order":3,"excluded":true},"rss":{"order":4,"excluded":true},"nntp":{"order":5,"excluded":true},"exquilla":{"order":6,"excluded":true}},"excludedAccounts":[]}
14:24:39.869 DEBUG firetray.Messaging sortByTypeAndName=false
14:24:39.869 DEBUG firetray.Messaging ACCOUNT: Gmail type: imap
14:24:39.869 DEBUG firetray.Messaging is servertype excluded: false, account exclusion index: -1
14:24:39.875 DEBUG firetray.Messaging newMsgCount=0
14:24:39.875 DEBUG firetray.Messaging folder: [Gmail] folderUnreadMsgCount=0
14:24:39.875 DEBUG firetray.Messaging newMsgCount=0
14:24:39.876 DEBUG firetray.Messaging newMsgCount=0
14:24:39.876 DEBUG firetray.Messaging newMsgCount=0
14:24:39.876 DEBUG firetray.Messaging newMsgCount=0
14:24:39.876 DEBUG firetray.Messaging ACCOUNT: Místní složky type: none
14:24:39.876 DEBUG firetray.Messaging is servertype excluded: true, account exclusion index: -1
14:24:39.876 DEBUG firetray.Messaging Total UnreadMessages=0
14:24:39.876 DEBUG firetray.Messaging updateIcon
PluralForm.jsm: Index #2 of '#1 unread message;#1 unread messages' for value 0 is invalid -- plural rule #8; called by firetray.Messaging.updateIcon
14:24:39.877 DEBUG firetray.Messaging 0 unread message
14:24:39.877 DEBUG firetray.GtkStatusIcon setIconImageDefault
14:24:39.877 DEBUG firetray.GtkStatusIcon GIcon.ptr(ctypes.UInt64("0x7fa34ede9c10"))
14:24:39.877 DEBUG firetray.GtkStatusIcon setIconTooltip, toolTipStr=Thunderbird
14:24:39.877 DEBUG firetray.Handler allWindowsVisible=true msgCountPositive=true
14:24:39.877 DEBUG firetray.Messaging runProcess=/home/MYUSER/mail_notify args=0
14:24:39.881 INFO firetray.Handler isChatProvided=true
14:24:39.882 DEBUG firetray.commons registred account-added for [object Object]
14:24:39.882 DEBUG firetray.commons registred account-removed for [object Object]
14:24:39.882 DEBUG firetray.Messaging sortByTypeAndName=false
14:24:39.882 DEBUG firetray.Messaging ACCOUNT: Gmail type: imap
14:24:39.883 DEBUG firetray.Messaging ACCOUNT: Místní složky type: none
14:24:39.883 DEBUG firetray.commons registred xpcom-will-shutdown for [object Object]
14:24:39.883 DEBUG firetray.commons registred profile-change-teardown for [object Object]
14:24:39.884 INFO firetray.Handler restoredWindowsCount=1
14:24:39.884 DEBUG firetray.commons registred mail-startup-done for [object Object]
JavaScript error: resource://firetray/FiretrayHandler.jsm, line 531: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]
PluralForm.jsm: Index #2 of '#1 day;#1 days' for value 5 is invalid -- plural rule #8; called by unitPluralForm
PluralForm.jsm: Index #2 of '#1 day;#1 days' for value 5 is invalid -- plural rule #8; called by unitPluralForm
14:24:40.83 DEBUG firetray.Handler mail-startup-done: [object ChromeWindow],null
14:24:40.97 DEBUG firetray.Messaging OnItemIntPropertyChanged BiffState for folder Gmail was 2 became 1 NEW MESSAGES=0
14:24:41.297 INFO firetray.Handler *** appStarted ***
14:24:41.297 DEBUG firetray.Messaging PrefObserver added
ShowInOut 1.1.2 appName=Thunderbird appVersion=38.0
ShowInOut with parseEncodeHeader
JavaScript warning: chrome://mailsummaries/content/accountSummary.js, line 69: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/accountSummary.js, line 175: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/accountSummary.js, line 179: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript error: chrome://mailsummaries/content/accountSummary.js, line 186: TypeError: redeclaration of let self
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 63: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 261: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 265: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 284: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 310: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 319: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 336: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 441: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 459: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 543: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
JavaScript warning: chrome://mailsummaries/content/folderSummary.js, line 667: JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
Loading folder summary for Složka
PluralForm.jsm: Index #2 of '#1 zpráv;#1 zpráva' for value 0 is invalid -- plural rule #8; called by FolderSummary_formatString
 regular
  took 0.002 seconds
14:24:49.512 DEBUG firetray.Messaging OnItemIntPropertyChanged FolderSize for folder Složka was 0 became 0 NEW MESSAGES=0
14:24:50.430 DEBUG firetray.Messaging OnItemIntPropertyChanged FolderSize for folder Doručená pošta was 130602686 became 130602686 NEW MESSAGES=0
14:24:54.760 DEBUG firetray.Messaging OnItemIntPropertyChanged FolderSize for folder Koš was 0 became 0 NEW MESSAGES=0
14:24:55.308 DEBUG firetray.Window unregister window
14:24:55.309 ERROR firetray.FiretrayWindow unknown window while lookup
14:24:55.310 ERROR firetray.Window can't unregister unknown window null
14:24:55.310 DEBUG firetray.Chrome windowsCount=0, visibleWindowsCount=0
14:24:55.311 DEBUG firetray.Chrome Firetray UNLOADED !
Unloading folder summary

14:24:56.10 DEBUG firetray.Handler xpcom-will-shutdown
14:24:56.11 DEBUG firetray.Handler Disabling Handler
14:24:56.11 DEBUG firetray.Messaging Disabling Messaging
14:24:56.12 DEBUG firetray.StatusIcon Disabling StatusIcon
14:24:56.13 DEBUG firetray.GtkStatusIcon Disabling GtkStatusIcon
14:24:56.13 DEBUG firetray.PopupMenu Disabling PopupMenu
14:24:56.14 DEBUG firetray.ctypes-utils Closing library gdk-x11-2.0
14:24:56.14 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/gdk.jsm
14:24:56.15 DEBUG firetray.ctypes-utils Closing library gio-2.0
14:24:56.15 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/gio.jsm
14:24:56.16 DEBUG firetray.ctypes-utils Closing library glib-2.0
14:24:56.17 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/glib.jsm
14:24:56.17 DEBUG firetray.ctypes-utils Closing library gobject-2.0
14:24:56.18 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/gobject.jsm
14:24:56.18 DEBUG firetray.ctypes-utils Closing library gtk-x11-2.0
14:24:56.18 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/gtk.jsm
14:24:56.19 DEBUG firetray.ctypes-utils Closing library c
14:24:56.19 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/libc.jsm
14:24:56.19 DEBUG firetray.ctypes-utils Closing library X11
14:24:56.20 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/x11.jsm
14:24:56.20 DEBUG firetray.ctypes-utils Closing library cairo
14:24:56.21 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/cairo.jsm
14:24:56.21 DEBUG firetray.ctypes-utils Closing library pango-1.0
14:24:56.21 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/pango.jsm
14:24:56.22 DEBUG firetray.ctypes-utils Closing library pangocairo-1.0
14:24:56.22 DEBUG firetray.ctypes-utils Unloading JS module resource://firetray/ctypes/linux/pangocairo.jsm
```

Apart from the problem with crashing, I cannot open Preferences dialog from the icon in the tray (but it works from extension manager), nothing happens when I click it, in the log I see:
```
18:2:32.911 DEBUG firetray.PopupMenu menu-popup
18:2:32.912 DEBUG firetray.PopupMenu ARGS=GtkStatusIcon.ptr(ctypes.UInt64("0x7f47d94f0740")), 3, 146883808, ctypes.voidptr_t(ctypes.UInt64("0x7f47dedd2640"))
JavaScript error: resource://firetray/FiretrayHandler.jsm, line 478: TypeError: firetray.Handler.windows[first] is undefined
JavaScript error: , line 0: Error: JavaScript callback failed, and an error sentinel was not specified.
```

Everything worked before I updated to Thunderbird 38. I tried to delete the profile (~/.thunderbird folder), but it did not help.

**Comment by foudfou** [comment] 2015-06-14 20:50
Thanks for detailed information. Could you precise "FireTray [...] does not work with Icedove" ? What are the symptoms ?
I see relevant errors in the debug output:
```
JavaScript error: chrome://messenger/content/tabmail.xml, line 1067: TypeError: tab is undefined
JavaScript error: resource://firetray/FiretrayHandler.jsm, line 531: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]
PluralForm.jsm: Index #2 of '#1 day;#1 days' for value 5 is invalid -- plural rule #8; called by unitPluralForm
```
I tested 135126a on TB38.0b6, but couldn't reproduce them... Which localized version of TB are you using ? 
BTW are there other error messages in the JS/Error-console (Ctrl-J) ?

**Comment by tom62** [comment] 2015-06-15 07:30
When I start Thunderbird (or Icedove) with FireTray installed, I see a new icon in the tray. When I close the window, I expect it to hide to the tray (that is what FireTray does), but it really closes (Thunderbird is no longer running) and the tray icon disappears.

There are no additional messages in Error console.

I use Czech localization, but changing it to English does not change anything.

I will try to provide a VirtualBox virtual machine to test it in a couple of days.

**Comment by tom62** [comment] 2015-06-15 12:10
I am sorry, but my internet connection is so slow that I cannot upload the VirtualBox image. However, the problem can be reproduced with live CD. If you want to try it:
 * download Debian Jessie KDE live http://cdimage.debian.org/debian-cd/current-live/i386/iso-hybrid/debian-live-8.1.0-i386-kde-desktop.iso
 * boot it (I used VirtualBox)
 * Alt+F2, type "konsole" and run it
 * install Icedove from experimental:
```
sudo su
echo "deb http://ftp.debian.org/debian unstable main" > /etc/apt/sources.list
echo "deb http://ftp.debian.org/debian experimental main" > /etc/apt/sources.list
apt-get update
apt-get -y -t experimental install icedove
```
 * run Icedove and install FireTray in it (requires restarting Icedove)
 * close Icedove window. It should hide to tray, but it does not, the windows closes, icon in tray disappears and you get error in console:
```
13:49:53.747 ERROR firetray.FiretrayWindow unknown window while lookup
13:49:53.748 ERROR firetray.Window can't unregister unknown window null
```

This can be reproduced also with Thunderbird 38b6 from [ppa:mozillateam/thunderbird-next](https://launchpad.net/~mozillateam/+archive/ubuntu/thunderbird-next) and also with official Mozilla package:
 * on the KDE live CD run:
```
wget "https://download.mozilla.org/?product=thunderbird-38.0.1&os=linux&lang=en-GB" -O thunderbird-38.0.1.tar.bz2
tar -jxvf thunderbird-38.0.1.tar.bz2
cd thunderbird
./thunderbird
```
 * install FireTray and close the window. Icon in tray will disappear.

**Comment by cedjo** [comment] 2015-06-16 09:18
Same issue on Manjaro 0.8.13 KDE, Firetray 0.5.6.1-signed and Thunderbird 38.0.1
error message: 
11:13:47.564 ERROR firetray.FiretrayWindow unknown window while lookup
11:13:47.565 ERROR firetray.Window can't unregister unknown window null

and Thunderbird closes and tray icon is disappearing.

**Comment by Shadow27374** [comment] 2015-06-16 18:20
Same problem here at Linux Mint 17.1 Cinnamon x64 with the newest Thunderbird 38.0.1.

**Comment by danbruegge** [comment] 2015-06-19 09:16
Same here on Archlinux with Xfce. 
Also in Thunderbird-nightly 41
I also discoverd that it will appear only on new installations. My old installation at home is still working with firetray and thunderbird.

**Comment by anarchpenguin** [comment] 2015-06-19 22:55
Temporary workaround until debugging can be completed is to use 0.4.8 and disable auto update. This will atleast restore your setup to a working condition.

**Comment by tom62** [comment] 2015-06-20 06:32
I confirm that this workaround (FireTray 0.4.8.1-signed with Thunderbird 38) works and I hope that the new version will be fixed.

**Comment by Shadow27374** [comment] 2015-06-20 13:16
How can I compile 0.4.8?

**Comment by anarchpenguin** [comment] 2015-06-20 15:14
https://addons.mozilla.org/en-us/thunderbird/addon/firetray/versions/ Best practice is to download it.

**Comment by Shadow27374** [comment] 2015-06-20 15:30
Thanks, that work!

**Comment by foudfou** [comment] 2015-06-21 19:34
@tom62 couldn't install experimental icedove on a fresh deb8 install:
```
root@debian:~# LANG=C apt-get -y -t experimental install icedove                                                                                                                                                                                                               
Reading package lists... Done                                                                                                                                                                                                                                                  
Building dependency tree                                                                                                                                                                                                                                                       
Reading state information... Done                                                                                                                                                                                                                                              
Some packages could not be installed. This may mean that you have                                                                                                                                                                                                              
requested an impossible situation or if you are using the unstable                                                                                                                                                                                                             
distribution that some required packages have not yet been created                                                                                                                                                                                                             
or been moved out of Incoming.                                                                                                                                                                                                                                                 
The following information may help to resolve the situation:                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                               
The following packages have unmet dependencies:                                                                                                                                                                                                                                
 icedove : Depends: libvpx2 (>= 1.4.0) but it is not installable                                                                                                                                                                                                               
E: Unable to correct problems, you have held broken packages.
```
Can you provide guidance ?

**Comment by tom62** [comment] 2015-06-21 20:01
@foudfou My mistake, I am sorry.

In those lines `echo...` there should be `>>`, not `>`, so these lines rewrote your `sources.list` completely. There must be `jessie`, `unstable` and `experimental` repositories, because `libvpx2` is only in `unstable` and new `icedove` only in `experimental`.

This should hopefully work in your situation:
```
cat << 'EOF' > /etc/apt/sources.list
deb http://ftp.debian.org/debian jessie main
deb http://ftp.debian.org/debian unstable main
deb http://ftp.debian.org/debian experimental main
EOF
apt-get update
apt-get -y -t experimental install icedove
```

Anyway, you can use also the official Mozilla binaries as I mentioned above, the package in `experimental` is still beta 5.

**Comment by vayerx** [comment] 2015-06-28 09:50
The same problem on Gentoo Linux (`TypeError, NS_ERROR_UNEXPECTED,..`):

    firetray 0.5.6
    thunderbird 38.0.1 (jit, jemalloc3)
    gtk+ 2.24.28, 3.16.3
    lxde 0.5.5

Firetray 0.4.8 works fine.

**Comment by danbruegge** [comment] 2015-07-01 05:51
I've updated back from Thunderbird 31 to 38.0.1 with FireTray 0.5.6.1. Now it works fine.

**Comment by Myppomeu** [comment] 2015-07-12 10:12
Do you need virtualbox VM to test bug?

**Comment by Shadow27374** [comment] 2015-07-12 13:11
Comes an update or do I have to live with the workaround?

**Comment by loverdrive** [comment] 2015-08-08 11:43
same issue here! Gentoo Linux with xfce4.12 and thunderbird 38.1 with Firetray 0.5.3.1

**Comment by foudfou** [comment] 2015-08-20 21:57
Ok, reproduced on a fresh debian KDE, thanks to @tom62's guidance.
The problem seems to be that the `mail.biff.show_tray_icon` preference doesn't exist anymore, at least in some environments. Although [it is still in the original source code](http://mxr.mozilla.org/comm-aurora/source/mail/components/preferences/general.xul#94).
I'll fix that shortly.

**Comment by foudfou** [comment] 2015-08-22 17:01
This should be fixed in 7da96977637e82. The fixed is applied on top of the `gtk3` branch on purpose. You should be able to [build](/foudfou/FireTray/wiki/Build) FireTray for testing.

**Comment by Shadow27374** [comment] 2015-08-22 23:33
make build
checking version consistency
checking loglevel
make: *** [check_loglevel] Fehler 1

**Comment by foudfou** [comment] 2015-08-22 23:49
@Shadow27374 the log level in `modules/logging.jsm` should be `Warn`. It's correctly set in 4d9816ee439dab.

**Comment by Shadow27374** [comment] 2015-08-22 23:52
I do not know what I must do . ^^

**Comment by foudfou** [comment] 2015-08-22 23:59
@Shadow27374 follow [the build instructions](/foudfou/FireTray/wiki/Build), but before `make build`, do `git checkout gtk3`.

**Comment by Shadow27374** [comment] 2015-08-23 00:08
THX it works! :+1:

**Comment by theGeekPirate** [comment] 2015-08-29 03:11
I can also verify that building the latest version from git has resolved this issue.

**Comment by foudfou** [comment] 2015-08-29 09:39
Thanks for testing.

**Closed by foudfou** 2015-08-29 09:39 UTC
